## 구현할 기능 목록

- 컴퓨터가 1~9까지 서로 다른 숫자 3자리 수 랜덤하게 생성해서 저장
- 사용자한테 숫자 입력 받기
- 사용자가 잘못된 값을 입력할 경우 
IllegalArgumentException을 발생시킨 후 애플리케이션 종료
- 컴퓨터가 저장한 값과 입력받은 값 비교하여 스트라이크, 볼 개수 카운트해서 저장
- 결과 출력
- 3 스트라이크가 아닐시 계속 진행
- 3 스트라이크일 경우 결과 출력 후 재시작/종료 안내 문구 출력
- 1 입력시 재시작 2 입력시 게임종료.
- 사용자가 입력을 잘못하지 않았는지 확인하는 메소드.


## 구현할 클래스
#### 1. Computer
#### 2. Player
#### 3. Operator
- Computer 인스턴스 생성
- Player 인스턴스 생성
- Computer 한테 랜덤 숫자 생성하라 명령
- Player 인스턴스 한테 숫자 입력 받으라 명령
- 둘의 숫자 비교. 스트라이크 볼 개수 변수로 저장
- 결과 출력


## 출력 문구 예시
#### 

- 입력한 수에 대한 결과를 볼, 스트라이크 개수로 표시

```
1볼 1스트라이크
```

- 하나도 없는 경우

```
낫싱
```

- 3개의 숫자를 모두 맞힐 경우

```
3스트라이크
3개의 숫자를 모두 맞히셨습니다! 게임 종료
```

- 게임 시작 문구 출력

```
숫자 야구 게임을 시작합니다.
``` 

## 예외 처리에 대한 고찰
- 사용자한테 입력 받는 곳은 두 곳
- 첫번째는 서로 다른 숫자 3자리 수 입력 받기
- 두번째는 게임 종료 후 재시작할지 말지 입력 받기
- 첫번째의 경우 서로 다른 숫자 3자리 인지 아닌지를 확인하고, 
아니라면 IllegalArgumentException을 발생시킨 후 애플리케이션 종료
- 두번째는 입력받은 문자열이 1 혹은 2가 아닐시,
  IllegalArgumentException을 발생시킨 후 애플리케이션 종료.
- Operator에서 알맞는 문자열인지 확인해야할듯.
- 발생시킨 후 종료 되어야 하니까 try, catch 처리하면 안되고 throw만 해줘야 할듯.

## 예외 처리에 대한 고찰 2
- 테스트코드는 정상적으로 동작함
- 그러나 제출하면 예기치 않은 오류로 인해 ..블라 블라 정상으로 진행 안됨
- 예외 처리에 문제가 있지 않을까 
- main에서 예외를 catch 하면 예외 발생시 어플리케이션 정상 종료. 그러나 테스트코드가 통과안됨
- main에서 예외를 catch 안해주거나, catch에서 새로운 예외 던져주면 테스트코드는 통과되지만, 어플리케이션이 정상 종료 안됨...
- 제출 오류는 이 문제가 아니었음.

## Operator.isCorrectNumber 
#### - 사용자가 입력을 잘못하지 않았는지 확인하는 메소드. 
- 길이가 3여야하고
- 요소가 모두 1~9 사이의 숫자여야 하고. // 이건 입력 받은 곳에서 처리함.
- 요소가 모두 다 다른 수 여야함.